[versions]
java = "21"
kotlin = "2.2.21"
coroutines = "1.10.2"
flatlaf = "3.6.1"
kotest = "6.2.3"
ignition = "8.1.20"
jackson = "2.20.1"

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
conveyor = { id = "dev.hydraulic.conveyor", version = "1.12" }
spotless = { id = "com.diffplug.spotless", version = "8.1.0" }
dokka = { id = "org.jetbrains.dokka", version = "2.1.0" }

[libraries]
# core functionality
coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-swing = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-swing", version.ref = "coroutines" }
serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version = "1.9.0" }
xerial-jdbc = { group = "org.xerial", name = "sqlite-jdbc", version = "3.51.1.0" }
logback = { group = "ch.qos.logback", name = "logback-classic", version = "1.5.18" }
hsql = { group = "org.hsqldb", name = "hsqldb", version = "2.7.4" }
poi = { group = "org.apache.poi", name = "poi-ooxml", version = "5.5.1" }
excelkt = { group = "io.github.evanrupert", name = "excelkt", version = "1.0.2" }
jsvg = { group = "com.github.weisj", name = "jsvg", version = "2.0.0" }
jackson-kotlin = { group = "com.fasterxml.jackson.module", name = "jackson-module-kotlin", version.ref = "jackson" }
jackson-xml = { group = "com.fasterxml.jackson.dataformat", name = "jackson-dataformat-xml", version.ref = "jackson" }

# build
jsoup = { group = "org.jsoup", name = "jsoup", version = "1.21.2" }

# appearance/swing
miglayout = { group = "com.miglayout", name = "miglayout-swing", version = "11.4.2" }
flatlaf-core = { group = "com.formdev", name = "flatlaf", version.ref = "flatlaf" }
flatlaf-extras = { group = "com.formdev", name = "flatlaf-extras", version.ref = "flatlaf" }
flatlaf-jide = { group = "com.formdev", name = "flatlaf-jide-oss", version.ref = "flatlaf" }
flatlaf-swingx = { group = "com.formdev", name = "flatlaf-swingx", version.ref = "flatlaf" }
flatlaf-themes = { group = "com.formdev", name = "flatlaf-intellij-themes", version.ref = "flatlaf" }
flatlaf-fonts-roboto = { group = "com.formdev", name = "flatlaf-fonts-roboto", version = "2.137" }
flatlaf-fonts-roboto-mono = { group = "com.formdev", name = "flatlaf-fonts-roboto-mono", version = "3.000" }
jide-common = { group = "com.formdev", name = "jide-oss", version = "3.7.15" }
swingx = { group = "org.swinglabs.swingx", name = "swingx-all", version = "1.6.5-1" }
rsyntaxtextarea = { group = "com.fifesoft", name = "rsyntaxtextarea", version = "3.6.0" }
jfreechart = { group = "org.jfree", name = "jfreechart", version = "1.5.6" }

# Ignition
ignition-common = { group = "com.inductiveautomation.ignition", name = "common", version.ref = "ignition" }
ignition-gateway = { group = "com.inductiveautomation.ignition", name = "gateway-api", version.ref = "ignition" }
# Ignition core types use classes from these libs (e.g. StringUtils, ImmutableMap), so we're forced to include these
apache-commons = { group = "org.apache.commons", name = "commons-lang3", version = "3.8.1" }
# This leads to a warning at runtime about multiple logging providers on the classpath, but is unavoidable
slf4j = { group = "org.slf4j", name = "slf4j-log4j12", version = "2.0.17" }
google-guava = { module = "com.google.guava:guava", version = "26.0-jre" }
ia-gson = { module = "com.inductiveautomation.ignition:ia-gson", version = "2.10.1" }
ia-jython = { module = "org.python:jython-ia", version = "2.7.3.5" }

# test framework
kotest-junit = { group = "io.kotest", name = "kotest-runner-junit5", version.ref = "kotest" }
kotest-assertions-core = { group = "io.kotest", name = "kotest-assertions-core", version.ref = "kotest" }

# questdb
questdb = { module = "org.questdb:questdb", version = "9.0.3" }

[bundles]
coroutines = [
    "coroutines-core",
    "coroutines-swing",
]
flatlaf = [
    "flatlaf-core",
    "flatlaf-extras",
    "flatlaf-jide",
    "flatlaf-swingx",
    "flatlaf-themes",
    "flatlaf-fonts-roboto",
    "flatlaf-fonts-roboto-mono",
]
jackson = [
    "jackson-kotlin",
    "jackson-xml",
]
kotest = [
    "kotest-junit",
    "kotest-assertions-core",
]
ignition = [
    "ignition-common",
    "ignition-gateway",
]
ia-transitive = [
    "apache-commons",
    "google-guava",
    "ia-gson",
    "ia-jython",
    "slf4j",
]
